### PR TITLE
Fix throw expression detection.

### LINKED ISSUE #56: Throw always counted as php 8.0 throw expression
Given a file that contains only the following throw statement:

```php
<?php

throw new RuntimeException();

```

Running the `features` commands reports the following:

```sh
 ------------- ----------------------------------------------- ------------ 
  PHP version   Feature count                                               
 ------------- ----------------------------------------------- ------------ 
  7.0           Parameter types                                          0  
  7.0           Return types                                             0  
  7.0           Strict declares                                          0  
  7.0           Space ship <=> operator                                  0  
 ------------- ----------------------------------------------- ------------ 
  7.1           Nullable type (?type)                                    0  
  7.1           Void return type                                         0  
  7.1           Class constant visibility                                0  
 ------------- ----------------------------------------------- ------------ 
  7.2           Object type                                              0  
 ------------- ----------------------------------------------- ------------ 
  7.3           Coalesce ?? operator                                     0  
 ------------- ----------------------------------------------- ------------ 
  7.4           Typed properties                                         0  
  7.4           Arrow functions                                          0  
  7.4           Coalesce assign (??=)                                    0  
 ------------- ----------------------------------------------- ------------ 
  8.0           Named arguments                                          0  
  8.0           Union types                                              0  
  8.0           Match expression                                         0  
  8.0           Nullsafe method call/property fetch                      0  
  8.0           Attributes                                               0  
  8.0           Throw expression                                         1  
  8.0           Promoted properties                                      0  
 ------------- ----------------------------------------------- ------------ 
  8.1           First-class callables                                    0  
  8.1           Readonly property                                        0  
  8.1           Intersection types                                       0  
  8.1           Enums                                                    0  
 ------------- ----------------------------------------------- ------------ 
  8.2           Readonly class                                           0  
 ------------- ----------------------------------------------- ------------ 
  8.3           Typed class constants                                    0  
 ------------- ----------------------------------------------- ------------ 
  8.4           Property hooks                                           0  
 ------------- ----------------------------------------------- ------------
```

It looks like `PhpParser\Node\Stmt\Throw_` was removed in php-parser 5.0, so every throw node will be an instance of `PhpParser\Node\Expr\Throw_`.

When `$node instanceof Expr\Throw_` I think it should only be considered an expression if `! $node->getAttribute('parent') instanceof Stmt\Expression`, otherwise it is considered a statement: https://github.com/nikic/PHP-Parser/blob/8c360e27327c8bd29e1c57721574709d0d706118/CHANGELOG.md#removed-1

### PR DESCRIPTION
**Pull request by ssnepenthe**
Requires adding ParentConnectingVisitor to node traverser

Fixes #56

### CODE REVIEW

**Comment by TomasVotruba** [comment]
The parent connecting visitor is very costly.
There must be some better way to detect it.

**Comment by ssnepenthe** [comment]
Yeah I wondered about that...

After some very naive testing against the symfony/dependency-injection package (~600 files) and the spatie/schema-org package (~1800 files) I was seeing a 20-25% increase in memory usage as reported by memory_get_peak_usage() and a 3-4% increase in actual run time.

I pushed some changes that seem to address the memory issue, but I didn't get consistent enough run time measurements to see if there was an improvement there.

Let me know what you think of this approach.

**Comment by TomasVotruba** [comment]
> The above actually finds all throw statements which is not what we want. If we want to find throw expressions we might try something like:


I see. In that case, you can make use of php-parser constants, e.g. `NodeVisitor::DON_TRAVERSE_CHILDREN`.
Then any following `Throw_` will **not be** standalone stmt.

File: src/FeatureCounter/NodeVisitor/ThrowExpressionFlaggingNodeVisitor.php [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+            return NodeVisitor::DONT_TRAVERSE_CHILDREN;
+        }
+
+        if ($node instanceof Throw_) {
+            $node->setAttribute('is_throw_expression', true);
+        }
+
+        return null;
+    }
+}
```
Comment (TomasVotruba) [inline src/FeatureCounter/NodeVisitor/ThrowExpressionFlaggingNodeVisitor.php]: This can happen directly in the `FeatureCollector`, no need to add this extra layer of complexity.

**Comment by TomasVotruba** [comment]
Neat, I like :+1:  Let's go with that approach. Thank you
